spring:
  profiles:
    active:
      - common      # 数据源基本配置
      - user
      - server
      - ${APP_ENV:dev}  # 运行环境
  mvc:
    throw-exception-if-no-handler-found: on
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
